amino_acids = ['alanine', 
       'arginine', 'aspartic_acid', 'cystine', 'glutamic_acid', 'glycine',
       'histidine', 'hydroxyproline', 'isoleucine', 'leucine', 'lysine',
       'methionine', 'phenylalanine', 'proline', 'serine', 'threonine',
       'tryptophan', 'tyrosine', 'valine',]
essential = ['histidine', 'isoleucine', 'leucine', 'lysine', 
                         'methionine', 'phenylalanine', 'threonine', 'tryptophan', 'valine']
macro_minerals = ['sodium', 'potassium', 'calcium', 'phosphorous','magnesium']
trace_minerals = ['copper','irom','manganese','zink','selenium']
vitamins = ['choline', 'riboflavin','thiamin','niacin','pantothenic_acid',
            'folate','folic_acid','vitamin_a','vitamin_b12','vitamin_b6',
            'vitamin_c','vitamin_d','vitamin_e','vitamin_k']
fatty_acids = ['saturated_fatty_acids','monounsaturated_fatty_acids',
               'polyunsaturated_fatty_acids']
summary = ['protein','carbohydrate','sugars','total_fat','saturated_fat','fiber']
other = ['cholesterol']

lower = {'total_fat': 50,
 'saturated_fat': 10,
 'cholesterol': 50,
 'sodium': 1500,
 'choline': 550,
 'folate': 400,
#  'folic_acid': 400,
 'niacin': 16,
 'pantothenic_acid': 5,
 'riboflavin': 1.3,
 'thiamin': 1.2,
 'vitamin_a': 3000,
 'vitamin_a_rae': ' mcg',
 'carotene_alpha': ' mcg',
 'carotene_beta': ' mcg',
 'cryptoxanthin_beta': ' mcg',
 'lutein_zeaxanthin': ' mcg',
 'vitamin_b12': 2.4,
 'vitamin_b6': 1.3,
 'vitamin_c': 90,
 'vitamin_d': 600,
 'vitamin_e': 15,
 'vitamin_k': 120,
 'calcium': 1300,
 'copper': 0.9,
 'irom': 8,
 'magnesium': 400,
 'manganese': 2.3,
 'phosphorous': 700,
 'potassium': 4700,
 'selenium': 55,
 'zink': 11,
 'protein': 70,
 'alanine': ' g',
 'arginine': ' g',
 'aspartic_acid': ' g',
 'cystine': 0.287,
 'glutamic_acid': ' g',
 'glycine': ' g',
 'histidine': 0.7,
 'hydroxyproline': 'g',
 'isoleucine': 1.4,
 'leucine': 2.73,
 'lysine': 2.1,
 'methionine': 0.728,
 'phenylalanine': 0.875,
 'proline': ' g',
 'serine': ' g',
 'threonine': 1.05,
 'tryptophan': 0.28,
 'tyrosine': 0.875,
 'valine': 1.82,
 'carbohydrate': 130, #130
 'fiber': 38,
 'sugars': 'g',
 'fructose': 'g',
 'galactose': 'g',
 'glucose': 'g',
 'lactose': 'g',
 'maltose': 'g',
 'sucrose': 'g',
 'fat': 'g', #78
 'saturated_fatty_acids': ' g',
 'monounsaturated_fatty_acids': ' g',
 'polyunsaturated_fatty_acids': 17,
 'alcohol': 'g',
 'ash': 'g',
 'caffeine': 'g',
 'theobromine': 'g',
 'water': 100} #500

upper = {'total_fat': 120,
 'saturated_fat': 25,
 'cholesterol': 250,
 'sodium': 3000,
 'choline': 2500,
 'folate': 900,
#  'folic_acid': 900,
 'niacin': 30,
 'pantothenic_acid': 100,
 'riboflavin': 500,
 'thiamin': 200,
 'vitamin_a': 8000,
 'vitamin_a_rae': ' mcg',
 'carotene_alpha': ' mcg',
 'carotene_beta': ' mcg',
 'cryptoxanthin_beta': ' mcg',
 'lutein_zeaxanthin': ' mcg',
 'vitamin_b12': 8,
 'vitamin_b6': 4,
 'vitamin_c': 1000,
 'vitamin_d': 5000,
 'vitamin_e': 500,
 'vitamin_k': 500,
 'calcium': 2000,
 'copper': 7,
 'irom': 35,
 'magnesium': 500,
 'manganese': 7,
 'phosphorous': 3500,
 'potassium': 7000,
 'selenium': 300,
 'zink': 35,
 'protein': 100,
 'alanine': ' g',
 'arginine': ' g',
 'aspartic_acid': ' g',
 'cystine': ' g',
 'glutamic_acid': ' g',
 'glycine': ' g',
 'histidine': ' g',
 'hydroxyproline': 'g',
 'isoleucine': ' g',
 'leucine': ' g',
 'lysine': ' g',
 'methionine': ' g',
 'phenylalanine': ' g',
 'proline': ' g',
 'serine': ' g',
 'threonine': ' g',
 'tryptophan': ' g',
 'tyrosine': ' g',
 'valine': ' g',
 'carbohydrate': 400, #300
 'fiber': 55,
 'sugars': 40,
 'fructose': ' g',
 'galactose': 'g',
 'glucose': ' g',
 'lactose': ' g',
 'maltose': ' g',
 'sucrose': ' g',
 'fat': 'g', #120
 'saturated_fatty_acids': ' g',
 'monounsaturated_fatty_acids': ' g',
 'polyunsaturated_fatty_acids': 30,
 'alcohol': 5,
 'ash': ' g',
 'caffeine': ' mg',
 'theobromine': ' mg',
 'water': 2000}